### ISSUE TITLE
Landing page for the dashboard

### ISSUE THREAD

**Issue by acs** [aylabs/iotfloss#13]
Right now if you go to https://iotfloss.bitergia.net/ you ar not redirected to the Git overview dashboard as it must be. @valeriocos could you change it? It is critical for the FOSDEM talk IMHO so people reach the correct place to start playing with the data.

**Comment by valeriocos** [comment]
Done, the landing page is now Git, the dashboard Overview has been removed.

**Comment by acs** [comment]
Cool. So we can start to share the URL: https://iotfloss.bitergia.net/

But probably I will do it after the FOSDEM ... what do you think  @valeriocos ?

**Comment by valeriocos** [comment]
sure!
