### ISSUE TITLE
Remove from the dashboards all the dasboards we don't plan to use

### ISSUE THREAD

**Issue by acs** [aylabs/iotfloss#15]
In order to offer a more stable service it is a good idea to remove all the dashboards that we don't plan to use. Maybe we can just remove them from the menu. What do you think @valeriocos ?

**Comment by valeriocos** [comment]
Done @acs, can you please have a look at the dashboards and see if we can close this issue ?

**Comment by acs** [comment]
Ok, let's close it. Probably there are more dashboards that after removing people data have little value but enough is enough for the 0.1 release. Closing!
