### ISSUE TITLE
Define the disclaimers to be included at the start

### ISSUE THREAD

**Issue by acs** [aylabs/iotfloss#16]
* IIoT by default
* Organizations not totally accurate based on email domains mainly

**Comment by valeriocos** [comment]
@acs , is this something to target in the dashboard or in the talk?
We can put in the landing dashboard a help text, which provides a quick overview of the data. WDYT?

**Comment by acs** [comment]
It is for the talk, but it could be also a good idea to put some information in the dashboard, probably at the bottom as you do in other places. It is not so visible but it is better than nothing probably!

**Comment by acs** [comment]
Disclaimers included ... closing this ticket also!
