### ISSUE TITLE
Define how the dashboard will be used in the FOSDEM 2020 talk

### ISSUE THREAD

**Issue by acs** [aylabs/iotfloss#4]
The IoT [dashboard](https://grimoirelab-incubator.biterg.io/) has a lot of cool information about IoT projects analyzed. But we need to define how we will use if, and will pages put the focus and howto link the story in the slides with the dashboard.

**Comment by acs** [comment]
We are going to label the repositories with the hope that we can create later some dashboard comparing projects (based on their repositories) based on labels. For example, that we can select the "integration" label and that all projects with this label in one of their repositories appear in the dashboard. Right @valeriocos ?

**Comment by valeriocos** [comment]
Yes! In order to add the labels to a repo, you can do as follows:
```
    "Camel": {
      "git": [
        "https://github.com/apache/camel --labels=[edge]"
      ],
      "github": [
        "https://github.com/apache/camel --labels=[edge]"
      ],
      "meta"       : { "title" : "Apache" }
    },
```

The labels will appear in the git and github enriched index within the attribute `repository_labels`

**Comment by acs** [comment]
Cool! And several labels can be added. Useful if a project can be under several categories. But I will try to have just one category per project to simplify.

**Comment by acs** [comment]
I have added the labels in the Apache projects to test it. If I have done it correctly I will do it for all the projects. Could you confirm it @valeriocos ? The commit is: https://github.com/aylabs/iotfloss/commit/bce296b509dd8b91d785e32b5d0c9015825b1155

**Comment by acs** [comment]
In the dashboard we have the categories now. So we can start designing how they will be show. Some initial ideas:
![Screenshot from 2020-01-09 07-31-57](https://user-images.githubusercontent.com/209533/72045905-892c3080-32b7-11ea-8b2c-490e0d7915b9.png)

**Comment by acs** [comment]
Right now my main concern is that we can not filter AFAIK by foundation. Maybe we need to retag all repositories to add a foundation tag (you can have several tags/label per repository). But I am checking it now. @valeriocos could you confirm that we need to add an extra label to classify the projects also by foundation? Thanks!

**Comment by acs** [comment]
I have found that in **cm_title** que have the title value in meta dict and in this field we have put the foundation, so we have it already. Great!

**Comment by acs** [comment]
Ok, so we can have three filters, one for Foundation, and then we need to combine them with OR, not with AND. I think that is possible, probably with AND and in the inverse logic:

**NOT Apache** AND **NOT Eclipse** AND **NOT Linux**

Just activating the filter remove the projects for the Foundation. So we can for example show projects for Apache and Eclipse with NOT Linux. To show the Eclipse projects:

![Screenshot from 2020-01-11 09-03-11](https://user-images.githubusercontent.com/209533/72201134-3c7c5d00-3451-11ea-8945-68c49e4120dd.png)

I will try to find a more natural way to do it, but this is a solution.

**Comment by acs** [comment]
Probably we need to create a new dashboard to compare the Foundations. If we start just with a dashboard comparing the number of commits, we can have viz aggregated by cm_title. Then we can filter by category and we have our dashboard to compare the projects by foundation and by category.

**Comment by acs** [comment]
I have created a first dashboard just to show the general idea: https://grimoirelab-incubator.biterg.io/goto/2d1ff05bd5e1abcac74ca4f92e8a266d

@valeriocos we must work in something like that. What do you think? Probably a kind of Overview panel but aggregated by Foundation and with a category filter.

![Screenshot from 2020-01-11 09-22-09](https://user-images.githubusercontent.com/209533/72201403-dfce7180-3453-11ea-8851-7ff6af6cf558.png)

**Comment by acs** [comment]
This is covered in https://github.com/aylabs/iotfloss/issues/7 so closing this ticket!
