### ISSUE TITLE
Review resources for the web dashboard server

### ISSUE THREAD

**Issue by acs** [aylabs/iotfloss#6]
We need to be sure that there won't be issues with the web server.

What resource do we have? Could the resources be upgraded? Do we have the ability to restart the server if there are problems?

**Comment by acs** [comment]
The new dashboard has now specific resources and it is located at:

https://iotfloss.bitergia.net/

Let's test it during the next two weeks!

**Comment by valeriocos** [comment]
Everything is running smoothly @acs

**Comment by valeriocos** [comment]
Can we close this issue @acs ?  the resources seem OK

**Comment by acs** [comment]
Great! Closing it!
