### ISSUE TITLE
Define how the Foundations will be compared

### ISSUE THREAD

**Issue by acs** [aylabs/iotfloss#7]
After thinking about how to implement the goal, compare the IoT projects in the FLOSS Foundations, I have reached a possible approach:

* Projects will be compared in each category using some criteria based on data like number of commits and committers, number of different orgs or number of months of activity of the project.
* For each category we will define a winner based on the above criteria.
* And the foundation with more winners will be overall winner.

It is a pretty naive approach, but it is based on data. The categories and howto compute category winners will be the keys to define the global winner. But I will remark that it is just a **game** just to show the landscape of FLOSS IoT projects and provide some starting insights.

Then the idea is try to open everything to the IoT community in order to define common categories defined from this community and also, define the criteria to evaluate the projects. This landscape must be a living one, and it should be a tool useful for FLOSS IoT.

Also, new projects must be added (NodeRED from JS Foundation for example).

This repository should be the one used to coordinate all the work.

What do you think @valeriocos ? Do you think the web dashboard could be updated and active after the talk?

**Comment by acs** [comment]
The idea is to have something similat to the Gartner magic quadrant but based on data collected with GrimoireLab and using some automatic rules to define the scores.

**Comment by valeriocos** [comment]
> What do you think @valeriocos ? Do you think the web dashboard could be updated and active after the talk?

That's possible, I have to check with some bitergians to have place to keep this data available. We did something similar in the past, so there shouldn't be problems.

**Comment by acs** [comment]
I plan to do a first review/comparison based on the current categories to see what the outcomes are. After this, we can decide if this approach is a valuable one. Stay tuned to this ticket! :)

**Comment by acs** [comment]
The [current categories](https://github.com/aylabs/iotfloss/issues/2#issuecomment-572422131) are:

1. protocol
2. persistence
3. os_virtualization
4. processing
5. integration/gateway
6. framework
7. platform
8. ecosystem
9. fog
10. application

So let's open a new comment per category to analyze it and to check if this approach generates insights.

**Comment by acs** [comment]
**protocol**

In this category we have included the projects related to the implementation of the different protocols used in IoT for the communication between the devices, assets and in general, the "things".

Eclipse is leading this category by number of projects, commits and by comunity size. But Apache has the most promising project (PLC4x), unifying different protocols (some of them using Eclipse implementations like Eclipse Milo for OPC-UA protocol) and creating a common layer for communicating with different IoT devices (mainly PLCs).

LF does no have projects in this category but probably, they are using some of the Eclipse projects for implementing protocol stuff, or they have protocols support implementation inside the framework and platform projects.

![Screenshot from 2020-01-13 20-37-25](https://user-images.githubusercontent.com/209533/72285995-88dbbe80-3644-11ea-8ba4-dbab28322203.png)

**Comment by acs** [comment]
**persistence**

Projects related with the persistence of the data processed in IoT platforms.

Just the Apache IoTdb project. There are also projects like Apacke Kafka, but it is not IoT specific so out of the scope of this report. In Apache there is also the [Apache Calcite](https://calcite.apache.org/) (dynamic data management framework) which is [integrated with IoTdb](http://mail-archives.apache.org/mod_mbox/iotdb-dev/201903.mbox/%3C23CF4BE7-69C6-44D8-9F7F-087FC88A0B66@pragmaticminds.de%3E). Also Apache has other projects like Apache HDFS, Spark ... all the Big Data projects which are used in IoT for Big Data processing.

So in this category, Apache is the clear winner. 

![Screenshot from 2020-01-13 21-47-32](https://user-images.githubusercontent.com/209533/72290828-5931b400-364e-11ea-9cdb-3b7117b80364.png)

**Comment by acs** [comment]
**os_virtualization**

In this category are the projects related to the OS installed in the things at the edge (normally RTOS like Zephyr), the container technologies used in this devices and also, the services to update the software in the constrained devices and the more complex gateways system in the edge.

![Screenshot from 2020-01-13 21-54-02](https://user-images.githubusercontent.com/209533/72291246-42d82800-364f-11ea-9dc1-f80747927a1b.png)

[Zephyr vs Mynewt](https://www.reddit.com/r/embedded/comments/9l7c8f/which_rtos_for_iot_zephyr_or_mynewt/)

Concierge is an OSGi implementation for edge devices. and Hawkbit is for distributing the software (a feature included in Mynewt AFAIR).

[PhotonOS](https://vmware.github.io/photon/) is included in the LF Edge architecture with Zephyr, but it is not a LF project, at least yet (it is from VMware).

[Eclipse eVe](https://www.lfedge.org/projects/eve/) is the bet to use virtualization technologies in the Edge.

In this category all the foundations are working hard with interesting projects, and there is not a clear winner. The Apache project Brooklyn could also be moved to this category probably.

**Comment by acs** [comment]
**processing**

![Screenshot from 2020-01-13 23-17-41](https://user-images.githubusercontent.com/209533/72296849-ed097d00-365a-11ea-98bd-2f31b8e0f051.png)

In this category maybe projects like Apache NiFi could also be added for data processing. Like in the case of persistence, Apache foundation is leading also this category. Edgent is now an archived project. [mxnet is about deep learning and could be applied in the edge](https://mxnet.apache.org/api/faq/smart_device). 

Eclipse or LF has nothing related to data processing as independent projects. Let's see if inside the frameworks and platforms, this features are included directly or they are based on existing projects.

**Comment by acs** [comment]
**integration/gateway**

Apache Camel is about: «Camel is an open source integration framework that empowers you to quickly and easily integrate various systems consuming or producing data.»

Apache NiFi is related to streaming data processing, so probably we should move it to data processing category.

[Camel and NiFi](https://stackshare.io/stackups/apache-camel-vs-apache-nifi)

Apache is another time the winner in this category, followed by Eclipse. Let's see how LF frameworks (EdgeX and Fledge) implements the integration.

![Screenshot from 2020-01-13 23-22-43](https://user-images.githubusercontent.com/209533/72297175-a1a39e80-365b-11ea-9190-cc02b272c512.png)

**Comment by acs** [comment]
**framework**

LF is leading here because of its global vision of Edge computing.

LF is the one building the complete frameworks in which to build IIoT platforms. IoTivity is a mature project in which [the Open Connectivity Foundation is implementing its standards](https://openconnectivity.org/developer/reference-implementation/iotivity/) (discovery and management of devices, data transmission and management). EdgeX is the core of the LF Edge strategy and its [the framework for implementing IIoT platforms](https://en.wikipedia.org/wiki/EdgeX_Foundry) and in special IIoT Edge systems.

![Screenshot from 2020-01-13 23-30-18](https://user-images.githubusercontent.com/209533/72297714-c2202880-365c-11ea-9608-023d981be245.png)

**Comment by acs** [comment]
**platform**

Eclipse and LF are both providing different platforms that provide systems to be used in IIoT platforms (or that are complete platforms, like Fledge or Mainflux). 

Eclipse provides more subplatforms of an IIoT platform, and LF provides the complete platform. It is pretty similar at what happens in protocol category and in general: Eclipse is providing the modules to build the platform, but not the integration (maybe this is different in fog category).

![Screenshot from 2020-01-13 23-38-27](https://user-images.githubusercontent.com/209533/72298187-d6b0f080-365d-11ea-8a8a-c58fec1f3773.png)

Apache Brooklyn must be moved to this category.

**Comment by acs** [comment]
**ecosystem**

Missing for some reason the Dronecode project.

![Screenshot from 2020-01-13 23-45-46](https://user-images.githubusercontent.com/209533/72298819-78850d00-365f-11ea-9558-3ecd0d2cc2d4.png)

**Comment by acs** [comment]
**fog**

These projects are the core of Eclipse Edge strategy. And probably they must be inside the framework or platform categories.

![Screenshot from 2020-01-13 23-46-02](https://user-images.githubusercontent.com/209533/72298883-a79b7e80-365f-11ea-80ab-9c092784b262.png)

**Comment by acs** [comment]
**application**

Apache Brooklyn must be moved to platform. Here the clear winner is Eclipse which already has several applications due to its longer history.

![Screenshot from 2020-01-13 23-49-53](https://user-images.githubusercontent.com/209533/72298923-bb46e500-365f-11ea-84df-c8fa4fc7f8d0.png)

**Comment by acs** [comment]
Actions:

* Create a new cloud category and move to it all the projects related with cloud interoperatiblity. We have edge, fog and cloud, which is a clear way to classify projects. In the edge we have sub categories (protocol, integration, os_virtualization, platform, framework ...) but it fog and cloud, we just have the main category  **there are no cloud specific projects**
* Move Apache NiFi to processing (data) **ok**
* Move Apache Brooklyn to cloud **no cloud category finally**
* ecosystem category ... can be merged in others categories? **better as a specific one**

**Comment by acs** [comment]
@valeriocos once the above actions are done, we can do the final collection of data with the data in the categories that we will show for the FLOSS IoT Landscape v1.0.

**Comment by acs** [comment]
@valeriocos I will tag as 0.1 the current projects.json and I won't change the data for the FOSDEM talk (just update it). Could you schedule a new download of all data? Thanks!

Now let's focus on howto compare them. I would focus on creating the comparison dashboard to be used for the FOSDEM talk. And also, leave the standard dashboards for getting other insights about the data.

**Comment by acs** [comment]
Reviewing the actual " iot_Compare_HideCategories " dashboard probably:

* It is not needed to include several categories at the same time
* Probably we can have a widget with all the categories. By default all categories will be shown and once you select one in this widget, you will get this category
* Metrics and data needed
  * Foundations
  * Commits: history and totals
  * Authors: history and totals
  * Projects
  * Organizations
* Git overview will be enough once we add the categories and foundation widgets: what do you think @valeriocos?

**Comment by acs** [comment]
Sample of the desired dashboard. Maybe there are better options than using pies, but they are attractive and put the focus on the important things: foundations, categories and organizations. It is really cool how the number of commits is similar between de Foundations.

![Screenshot from 2020-01-16 19-07-33](https://user-images.githubusercontent.com/209533/72550778-bff3df00-3893-11ea-8c5e-6e1e5c7c0327.png)

**Comment by acs** [comment]
Another improvement in the commits and authors time series: group by Foundation.

![Screenshot from 2020-01-17 07-00-33](https://user-images.githubusercontent.com/209533/72588011-3b3aac80-38f7-11ea-8316-cc0b7351f655.png)

**Comment by acs** [comment]
The above dashboard will be the used in FOSDEM 2020 so this ticket is closed!

Once I create it in the final dashboard, of course.

**Comment by acs** [comment]
Ok, the final dashboard hs been created. It is the same than above but with some improvements.
![Screenshot from 2020-01-20 07-10-53](https://user-images.githubusercontent.com/209533/72702766-24dd5c80-3b54-11ea-88c8-8ce38a6d5fe9.png)

* More global metrics (org, projects)
* Added labels to commits time series
